//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subdomains
    {
        public Subdomains()
        {
            this.Questions = new HashSet<Questions>();
        }
    
        public int Id { get; set; }
        public string SubdomainName { get; set; }
        public int IdDomain { get; set; }
    
        public virtual Domains Domains { get; set; }
        public virtual ICollection<Questions> Questions { get; set; }
    }
}
