//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestQuestions
    {
        public TestQuestions()
        {
            this.Tests = new HashSet<Tests>();
            this.Tests1 = new HashSet<Tests>();
            this.Tests2 = new HashSet<Tests>();
            this.Tests3 = new HashSet<Tests>();
            this.Tests4 = new HashSet<Tests>();
            this.Tests5 = new HashSet<Tests>();
            this.Tests6 = new HashSet<Tests>();
            this.Tests7 = new HashSet<Tests>();
            this.Tests8 = new HashSet<Tests>();
            this.Tests9 = new HashSet<Tests>();
        }
    
        public int Id { get; set; }
        public int IdQuestion { get; set; }
        public string UserAnswer { get; set; }
        public string UserArgumentation { get; set; }
    
        public virtual Questions Questions { get; set; }
        public virtual ICollection<Tests> Tests { get; set; }
        public virtual ICollection<Tests> Tests1 { get; set; }
        public virtual ICollection<Tests> Tests2 { get; set; }
        public virtual ICollection<Tests> Tests3 { get; set; }
        public virtual ICollection<Tests> Tests4 { get; set; }
        public virtual ICollection<Tests> Tests5 { get; set; }
        public virtual ICollection<Tests> Tests6 { get; set; }
        public virtual ICollection<Tests> Tests7 { get; set; }
        public virtual ICollection<Tests> Tests8 { get; set; }
        public virtual ICollection<Tests> Tests9 { get; set; }
    }
}
