//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsAzureDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public Questions()
        {
            this.TestQuestions = new HashSet<TestQuestions>();
        }
    
        public int Id { get; set; }
        public string Question { get; set; }
        public string Answers { get; set; }
        public int RightAnswer { get; set; }
        public string Argumentation { get; set; }
        public bool TypeOfQuestion { get; set; }
        public int IdSubdomain { get; set; }
    
        public virtual Subdomains Subdomains { get; set; }
        public virtual ICollection<TestQuestions> TestQuestions { get; set; }
    }
}
