//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsAzureDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tests
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdTestQuestion1 { get; set; }
        public int IdTestQuestion2 { get; set; }
        public int IdTestQuestion3 { get; set; }
        public int IdTestQuestion4 { get; set; }
        public int IdTestQuestion5 { get; set; }
        public int IdTestQuestion6 { get; set; }
        public int IdTestQuestion7 { get; set; }
        public int IdTestQuestion8 { get; set; }
        public int IdTestQuestion9 { get; set; }
        public int IdTestQuestion10 { get; set; }
    
        public virtual TestQuestions TestQuestions { get; set; }
        public virtual TestQuestions TestQuestions1 { get; set; }
        public virtual TestQuestions TestQuestions2 { get; set; }
        public virtual TestQuestions TestQuestions3 { get; set; }
        public virtual TestQuestions TestQuestions4 { get; set; }
        public virtual TestQuestions TestQuestions5 { get; set; }
        public virtual TestQuestions TestQuestions6 { get; set; }
        public virtual TestQuestions TestQuestions7 { get; set; }
        public virtual TestQuestions TestQuestions8 { get; set; }
        public virtual TestQuestions TestQuestions9 { get; set; }
        public virtual Users Users { get; set; }
    }
}
